### ISSUE TITLE
❓Is this project dead?

### ISSUE THREAD

**Issue by soyjavi** [afterburn/hypernode#1]
Hi,

Are you working on TCP/Websocket implementation? I really would like use your *lib* but UDP is not enough.

Best,

**Comment by afterburn** [comment]
Hi soyjavi,

First of all thank you for wanting to use my library. I'm currently working on restructuring the way Hypernode is set up to allow for more modularity when it comes to choosing what transport(s) you want to use. I have a major release scheduled for november which will at least allow you to also make use of TCP as a transport.

Kind regards.
